language: node_js
node_js:
- 9.3.0
before_install:
- npm install -g @angular/cli
install: npm install
branches:
  only:
  - production
deploy:
  provider: heroku
  api_key:
    secure: Hm3Bo6xrcqZdRqIr9hMDkyk9tjyArLhnTWl76QpcZXY5D8lG9e/U61gbS0T2B/zAvScc1Q9XpLUfgmiEMiNPNScD0rnh4ouQlrujKvMpdRZnVzX6Fm/trArJYcMbYLiccK4gocKxMp+5w1FfEcc1SRVFrDqrWcfPQQzTuoZr72td6zhQALHkwAnjmo6R6N+SOKSZMgP3qpRLWclTV33ejH+kK1z55P56zmTzzdP2J1Gc/jY3qJWvmJnwPHMqPmt7Z08k/vDV0VMdW0S8/grPUylHRFfT5LyhZ0iZoQmOWt6dTzEmeZOWbegppVl9ewgvifpfYDDHVDVw7PlMU08vLuvJC3cGCA88XCSKbjYXYUKJi2rJWrwioFREJuQE4P0K6i+IyUs+9f0H6hJp2g2yqgNzgTSHxLYIJOFK7HiZdO6Y8V6mTdSmyALsXZ46W1f/ePHLHBMa1/2ruCV9Uvl2PB5nJTu8oaR9iSV1Zlkd4p3lo0eJYHGFtQEytuHZJW/o//OuCEAEHnLyFlIh8pRIF0yPsRFzsV7FVnI8UQBNAl75Llin4UD2nf7H0Yy9/fW7FV29pFnJ5ZH6NWyVErPPJ0EbkmTImXueK2wOaWlYSSUj52QLyjrXFeOUJUXnuJy1zFqccCxIKjjZ+f0Sjj50hn6CmNRlNKxpxOajQfa9vFA=
  app: l2sp
  on:
    repo: spaceisstrange/lastfm2spotify
